apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonic-notifications
  name: tonic-notifications
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-notifications
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-notifications
    spec:
      containers:
      - env:
        - name: TONIC_DB_DATABASE
          value: {{ .Values.tonicdb.dbname }}
        - name: TONIC_DB_USERNAME
          value: {{ .Values.tonicdb.user }}
        - name: TONIC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tonic-db-password
              key: password
        - name: TONIC_DB_PORT
          value: {{quote .Values.tonicdb.port }}
        - name: TONIC_DB_SSLMODE
          value: {{ .Values.tonicdb.sslMode }}
        - name: TONIC_DB_HOST
          value: {{ .Values.tonicdb.host }}
        {{- if .Values.tonicSmtpConfig.tonicUrl }}
        - name: TONIC_URL
          value: {{ .Values.tonicSmtpConfig.tonicUrl }}
        {{- end}}
        {{- if .Values.tonicSmtpConfig.sendingAddress }}
        - name: TONIC_NOTIFICATION_SENDING_ADDRESS
          value: {{ .Values.tonicSmtpConfig.sendingAddress }}
        {{- end}}
        {{- if .Values.tonicSmtpConfig.smtpServerAddress }}
        - name: TONIC_NOTIFICATION_SMTP_SERVER_ADDRESS
          value: {{ .Values.tonicSmtpConfig.smtpServerAddress }}
        {{- end}}
        {{- if .Values.tonicSmtpConfig.smtpServerPort }}
        - name: TONIC_NOTIFICATION_SMTP_SERVER_PORT
          value: {{quote .Values.tonicSmtpConfig.smtpServerPort }}
        {{- end}}
        {{- if .Values.tonicSmtpConfig.smtpUsername }}
        - name: TONIC_NOTIFICATION_SMTP_USERNAME
          value: {{ .Values.tonicSmtpConfig.smtpUsername }}
        {{- end}}
        {{- if .Values.tonicSmtpConfig.smtpPassword }}
        - name: TONIC_NOTIFICATION_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tonic-smtp-password
              key: password
        {{- end}}
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        - name: TONIC_NOTIFICATIONS_HEALTH_PORT_HTTP
          value: "7000"
        - name: TONIC_NOTIFICATIONS_HEALTH_PORT_HTTPS
          value: "7001"
        image: quay.io/tonicai/tonic_notifications:{{ .Values.tonicVersion }}
        imagePullPolicy: ""
        name: tonic-notifications
        ports:
        - containerPort: 7000
        - containerPort: 7001
        resources: {}
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
      - name: tonicai-build-writer-pull-secret
      serviceAccountName: ""
      volumes: null
status: {}
